spring:
  application:
    name: backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: postgres
    password: YOUR_PASSWORD_HERE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: YOUR_SECRET_KEY_HERE_MAKE_IT_LONG
  expiration: 86400000